# Introducción a Numpy y algunas operaciones básicas

<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="30%">

Numpy es una biblioteca para el lenguaje de programación Python que da soporte para crear matrices multidimensionales, junto con una gran colección de funciones de alto nivel para operar con ellas.

Su uso es muy sencillo, lo primero es convertir un vector o lista a un array numpy

In [1]:
import numpy as np

Crear un array 1-d

In [2]:
V = np.array([1,2,3,4,5])
V

array([1, 2, 3, 4, 5])

Se puede acceder elemento a elemento igual que a una lista

In [3]:
V[3]

4

Incluso a varios valores a la vez

In [4]:
V[[1, 3, 4]]

array([2, 4, 5])

Crear un array 1-d a partir de una lista de Python

In [5]:
L = [1, 2, 3, 4, 5, 6]

V = np.array(L)
V

array([1, 2, 3, 4, 5, 6])

# Tipos de vector

A diferencia de las listas, un vector o matriz Numpy sólo tener valores del mismo tipo.

In [6]:
np.array([1, 2, "hola"])

array([&#39;1&#39;, &#39;2&#39;, &#39;hola&#39;], dtype=&#39;&lt;U21&#39;)

Normalmente de tipo numérico

In [7]:
np.array([1, 2, 3.5])

array([1. , 2. , 3.5])

Se puede indicar el tipo al construirlo, con dtype {np.int, np.float32, np.float64})

In [8]:
A=np.array(L, dtype=np.float32)
A

array([1., 2., 3., 4., 5., 6.], dtype=float32)

# Ventaja de vector de tipo numpy

La principal ventaja es el tiempo, las operaciones en listas son muy lentas, y Numpy están implementadas eficientemente en C++. 

In [9]:
def norm1(vector):
    if len(vector)==0:
        return []
    
    maxv = minv = vector[1]
    
    for val in vector:
        if val > maxv:
            maxv = val
        elif val < minv:
            minv = val
    
    norm = len(vector)*[None]
    
    for i, val in enumerate(vector):
        norm[i] = (val-minv)/(maxv-minv)
        
    return norm    

In [10]:
# Creo un vector aleatorio
v = np.random.rand(1_000_000)
v_list = v.tolist()

In [11]:
%time sal1=norm1(v)

CPU times: user 766 ms, sys: 125 ms, total: 891 ms
Wall time: 907 ms


Lo implementamos ahora con numpy

In [12]:
def norm2(vector):
    minv = vector.min()
    maxv = vector.max()
    return (vector-minv)/(maxv-minv)

In [13]:
%time sal2=norm2(v)

CPU times: user 15.6 ms, sys: 31.2 ms, total: 46.9 ms
Wall time: 48.4 ms


In [14]:
assert np.all(sal1 == sal2)

# Operaciones vectoriales

Se puede sumar, restar, dividir, ... un vector por un escalar, y hace la operación elemento a elemento.

In [15]:
A/5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2], dtype=float32)

In [16]:
np.array([1.0,2,3,4,5]) / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

También se puede operar con vectores de igual tamaño, y hace la operación elemento a elemento

In [17]:
L

[1, 2, 3, 4, 5, 6]

In [18]:
M = np.array([2, 3, 4, 5, 6, 7])

P = L * M
P

array([ 2,  6, 12, 20, 30, 42])

También posee operaciones que trabajan con todos los elementos de un vector

In [19]:
P.sum()

112

In [20]:
# Desordeno
np.random.shuffle(P)

In [21]:
P

array([30,  6, 42, 12,  2, 20])

In [22]:
print(P.min(), P.max())

2 42


In [23]:
print(P.min(), np.argmin(P), P[np.argmin(P)])

2 4 2


También posee operaciones con vectores 

Producto escalar de dos vectores

In [24]:
np.dot(L, M)

112

# Crear un array 2-d

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[8,7,6]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 7, 6]])

shape da el tamaño (filas, columnas)

In [26]:
A.shape

(4, 3)

In [27]:
A[0,1]

2

In [28]:
A[2,1]

8

También se puede acceder a una fila o columna concreta

In [29]:
A[1,:]

array([4, 5, 6])

In [30]:
A[:,1]

array([2, 5, 8, 7])

Se puede acceder a un subconjunto

In [31]:
A[1:,1:]

array([[5, 6],
       [8, 9],
       [7, 6]])

In [32]:
A[1:3,1:]

array([[5, 6],
       [8, 9]])

In [33]:
A[1:,0:2]

array([[4, 5],
       [7, 8],
       [8, 7]])

También es fácil obtener los valores que cumplen un criterio

In [34]:
V = np.array([1, 2, 3, 4, 5, 6])

In [35]:
V > 3

array([False, False, False,  True,  True,  True])

In [36]:
V[V > 3]

array([4, 5, 6])

In [37]:
Ind = (V > 1) & (V < 6)
print(Ind)
V[Ind]

[False  True  True  True  True False]


array([2, 3, 4, 5])

# Creación

Numpy posee muchos métodos de generación aleatoria, normal, ..., muy útiles.

In [38]:
np.random.randint(10)

4

In [39]:
np.random.rand(10)

array([0.98281893, 0.33314843, 0.54989359, 0.73928024, 0.12579487,
       0.84254458, 0.24846603, 0.76950769, 0.06652931, 0.20479135])

In [40]:
np.random.randint(-10, 10, 5)

array([-5, -9,  7,  3,  4])

También hay otros métodos útiles

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Ejercicio Numpy

1. Crear una función que calcule la distancia euclídea entre dos vectores.

In [55]:
def disteuc(vector1, vector2):
    dist = None
    dist = np.sqrt(np.sum(np.power(vector1 - vector2, 2)))
    return dist

In [56]:
def test():
    assert 5 == disteuc(np.zeros(25), np.ones(25))
    assert 0 == disteuc(np.arange(30), np.arange(30))
    
test()